unique_ids:
  forms:
    Home.StuffCard: 3HVXYSIHLUC2NRLU7JB3QFPDUPUVU52M
    Base: WW4N3SHMFNJWWRXU4SR3QSYLWYXLZ2CG
    SetbackBotChallengeCard: CTAJPZ5AGZJI5COBTYPJ4A6G7ZNVG5UU
    Cribbage: EWGQCZ2QHKJXO6TFTRSR66XRYYYDCU3S
    Setback: YD4TPQJTZZXSADHHAIKSURA53O3EXVUB
    ToDo: LLRYKW7LH7UVSPAR7ZQHN5EBADW23PC2
    ToDo.RowTemplate1: O5RLJ3R3IMKXMRQFZ2DOARCC4SOJAU5R
    Setback.SetbackBotChallenge: YSTW7HR5ZOUMEEKI3BVZUGTH6ZEFCWZ2
    Home: AJLO7WNEH2TVHGL7U7KZMSQPI66GAS4Q
  modules:
    Setback.SetbackModule: RCNPVYE7HOJEPPVJW46P3PEOTUPPTEMO
  server_modules:
    StuffDetails: NDEEJ2NKDYXCE36CQZEAY66UYAO5A2HS
  assets:
    face.png: 7Z6FCOHROBU2Q5IGJ3MOJYXMS7RKJQK2
    green_felt.png: ORMXNQX624ETC4CF3Q3LOQUS3NQ6NV6S
    standard-page.html: UVHCQPLHAEKVHO6Z7IRRO7RHXEJGA4DU
    theme.css: PMWPJN6FOO4ADU7I7VOEO72J4NP7D3IN
