unique_ids:
  forms: {Base: CBMBWJR6UXBHXIJGY2PDBOBFUQ3A6XO4, Cribbage: EWGQCZ2QHKJXO6TFTRSR66XRYYYDCU3S,
    Home: AJLO7WNEH2TVHGL7U7KZMSQPI66GAS4Q, Setback: YD4TPQJTZZXSADHHAIKSURA53O3EXVUB}
  modules: {Base.Module1: R5LNSOL75PDGTITA7S7NLPKDV7SSRIP6}
  server_modules: {}
  assets: {face.png: KQKSV4KR7HOBF5OHJKF43TWEX6RVWXUH, standard-page.html: UVHCQPLHAEKVHO6Z7IRRO7RHXEJGA4DU,
    theme.css: PMWPJN6FOO4ADU7I7VOEO72J4NP7D3IN}
