unique_ids:
  forms: {Base: WW4N3SHMFNJWWRXU4SR3QSYLWYXLZ2CG, Cribbage: EWGQCZ2QHKJXO6TFTRSR66XRYYYDCU3S,
    Home: AJLO7WNEH2TVHGL7U7KZMSQPI66GAS4Q, Setback: YD4TPQJTZZXSADHHAIKSURA53O3EXVUB}
  modules: {Setback.SetbackModule: RCNPVYE7HOJEPPVJW46P3PEOTUPPTEMO}
  server_modules: {}
  assets: {face.png: 7Z6FCOHROBU2Q5IGJ3MOJYXMS7RKJQK2, green_felt.png: KTMWXTMKXRDH6GW5UAMBJKBBHHZKZ2EC,
    standard-page.html: UVHCQPLHAEKVHO6Z7IRRO7RHXEJGA4DU, theme.css: PMWPJN6FOO4ADU7I7VOEO72J4NP7D3IN}
